services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: unless-stopped

    ports:
      - "${SERVER_PORT}:25565"
      - "${RCON_PORT}:25575"

    environment:
      EULA: "TRUE"
      VERSION: "${MC_VERSION}"
      TYPE: "${MODLOADER}"
      MEMORY: "${MEMORY:-4G}"

      # Optional server settings
      DIFFICULTY: "${DIFFICULTY:-normal}"
      MODE: "${MODE:-survival}"
      MOTD: "${MOTD:-A Minecraft Server}"
      ONLINE_MODE: "${ONLINE_MODE:-true}"

      # RCON
      ENABLE_RCON: "${ENABLE_RCON:-false}"
      RCON_PASSWORD: "${RCON_PASSWORD:-change-me}"

    volumes:
      - ./data:/data


  webpage:
    image: nginx:alpine
    container_name: webpage
    restart: unless-stopped

    ports:
      - "${WEB_PORT}:80"

    volumes:
      - ./webpage:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro