volumes:
  RPG-Minecraft-Volume:
    external: true

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: unless-stopped

    ports:
      - "42065:25565"

    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "NEOFORGE"
      MEMORY: "4G"
      DIFFICULTY: "hard"
      MODE: "survival"
      MOTD: "Tukkercraft 3! Want het kan altijd meer ;)"
      ENABLE_RCON: "false"
      JVM_XX_OPTS: "-XX:+UseZGC"

    volumes:
      - RPG-Minecraft-Volume:/data
      - ./mods:/data/mods
      - ./config:/data/config
      - ./whitelist.json:/data/whitelist.json
      - ./ops.json:/data/ops.json



  # webpage:
  #   build: .
  #   container_name: webpage
  #   restart: unless-stopped

  #   ports:
  #     - "${WEB_PORT}:8080"

  #   volumes:
  #     - ./mods.mrpack:/app/mods.mrpack:ro
  #     - ./src:/app/src:ro
    
  #   environment:
  #     - SERVER_IP=${SERVER_IP:-localhost}
  #     - SERVER_PORT=${SERVER_PORT:-25565}
  #     - WEB_PORT=${WEB_PORT:-8080}
  #     - MC_VERSION=${MC_VERSION:-1.21.1}
  #     - MODLOADER=${MODLOADER:-neoforge}
  #     - MOTD=${MOTD:-Tukkercraft 3 - Cappie Server}
    
  #   depends_on:
  #     - minecraft